---
- name: Use the myvhost role
  hosts:  dns.example.com
  pre_tasks:
    - name: Display the pretasks message
      ansible.builtin.debug:
        msg:  'Ensure the web server is configured.'

  roles:
    - himzy.myvhost

  post_tasks:
    - name: Ensure that the html content is installed.
      ansible.builtin.copy:
        src:  index.html
        dest: /var/www/html/index.html

    - name: Post tasks message
      ansible.builtin.debug:
        msg:  'The webserver has been configured.' 
